require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.0.3
  NewCops: enable
  Exclude:
    - db/**/*
    - bin/*
    - .simplecov
    - tmp/**/*
    - vendor/**/*
    - node_modules/**/*

Metrics/BlockLength:
  Enabled: false
  AllowedMethods:
    - describe
    - context
    - it
    
Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Metrics/MethodLength:
  Max: 20
  Exclude:
    - spec/**/*

RSpec/NestedGroups:
  Max: 10

RSpec/MultipleMemoizedHelpers:
  Enabled: false

