version: "3.9"

services:

  postgres:
    container_name: bookshelf-db
    image: postgres:14.2
    environment:
      POSTGRES_USER: bookshelf
      POSTGRES_PASSWORD: bookshelf
    ports: 
      - '5432:5432'
    volumes:
      - bookshelf-postgres:/var/lib/postgresql/data

  redis:
    container_name: bookshelf-redis
    image: redis:7.0
    ports:
      - '6379:6379'
    volumes:
      - bookshelf-redis:/var/lib/redis/data

  bookshelf:
    container_name: bookshelf-app
    build:
      context: .
      dockerfile: ./Dockerfile.local
    volumes:
      - .:/bookshelf
    links:
      - postgres
      - redis
    ports:
      - '8010:8010'
    env_file:
      - .env
    command: 'bash -c redis-server'

  nginx:
    container_name: bookshelf-nginx
    build:
      context: .
      dockerfile: ./Dockerfile.nginx
    links:
      - bookshelf
    ports:
      - '8020:8020'

volumes:
  bookshelf-postgres:
  bookshelf-redis: